#!/usr/bin/env python3
"""Generate the robot sales ROI spreadsheet + pitch deck + zip bundle.

This script creates the following files under assets/robot-sales/:
- ROI.xlsx
- pitch.pptx
- robot-sales-materials.zip

Note: GitHub's file API in this environment cannot upload binary Office files directly,
so this script is the repo-native way to create the actual deliverables locally.
"""

from __future__ import annotations
import csv
import zipfile
from pathlib import Path
from datetime import datetime
from typing import Iterable

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment
except Exception:  # pragma: no cover
    Workbook = None

try:
    from pptx import Presentation
except Exception:  # pragma: no cover
    Presentation = None

ROOT = Path(__file__).resolve().parent
OUT_DIR = ROOT


def write_csv_template(path: Path) -> None:
    rows = [
        ["Item", "Value", "Note"],
        ["设备单价（一次性购置）", "200000", "¥"],
        ["安装/改造费用（一次性）", "20000", "¥"],
        ["培训与初期调试费用（一次性）", "10000", "¥"],
        ["总一次性投入", "=B2+B3+B4", "公式"],
        ["月维护费", "3000", "¥/月"],
        ["月耗材/能耗变化", "1000", "¥/月"],
        ["可替代厨房员工数", "2", "人"],
        ["单个员工税前月薪（含社保）", "6000", "¥/月"],
        ["月度人工节约", "=G7*H7", "公式"],
        ["运营天数/月", "26", "天"],
        ["当前日均订单", "120", "单"],
        ["采用机器人后日均订单", "150", "单"],
        ["日均新增订单", "=L12-L11", "公式"],
        ["平均客单价", "28", "¥/单"],
        ["月度新增营收", "=N13*N14*J10", "公式"],
        ["平均毛利率", "0.60", "0-1"],
        ["月度新增毛利", "=O15*P15", "公式"],
        ["其他月度新增成本/节省", "0", "¥/月"],
        ["月度净收益", "=J9+Q15-J5-J6+Q16", "公式"],
        ["回收期（个月）", "=B5/Q17", "公式"],
        ["年化ROI", "=Q17*12/B5", "公式"],
    ]
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerows(rows)


def build_minimal_xlsx(path: Path) -> None:
    """Write a minimal XLSX workbook manually using zipfile.

    This is intentionally compact and portable; if openpyxl is present, use that.
    """
    if Workbook is not None:
        wb = Workbook()
        ws = wb.active
        ws.title = "ROI"
        rows = [
            ["Item", "Value", "Note"],
            ["设备单价（一次性购置）", 200000, "¥"],
            ["安装/改造费用（一次性）", 20000, "¥"],
            ["培训与初期调试费用（一次性）", 10000, "¥"],
            ["总一次性投入", "=B2+B3+B4", "公式"],
            ["月维护费", 3000, "¥/月"],
            ["月耗材/能耗变化", 1000, "¥/月"],
            ["可替代厨房员工数", 2, "人"],
            ["单个员工税前月薪（含社保）", 6000, "¥/月"],
            ["月度人工节约", "=G7*H7", "公式"],
            ["运营天数/月", 26, "天"],
            ["当前日均订单", 120, "单"],
            ["采用机器人后日均订单", 150, "单"],
            ["日均新增订单", "=L12-L11", "公式"],
            ["平均客单价", 28, "¥/单"],
            ["月度新增营收", "=N13*N14*J10", "公式"],
            ["平均毛利率", 0.60, "0-1"],
            ["月度新增毛利", "=O15*P15", "公式"],
            ["其他月度新增成本/节省", 0, "¥/月"],
            ["月度净收益", "=J9+Q15-J5-J6+Q16", "公式"],
            ["回收期（个月）", "=B5/Q17", "公式"],
            ["年化ROI", "=Q17*12/B5", "公式"],
        ]
        ws.append(["", "", ""])
        for row in rows:
            ws.append(row)
        ws["A1"].font = Font(bold=True)
        ws["B1"].font = Font(bold=True)
        ws["C1"].font = Font(bold=True)
        for row in range(1, ws.max_row + 1):
            for col in ["A", "B", "C"]:
                ws[f"{col}{row}"].alignment = Alignment(horizontal="left")
        wb.save(path)
        return

    # Minimal XLSX generated by hand. This is a valid OOo XML zip package.
    # It uses simple cell entries and should open in Excel.
    rows = [
        ["Item", "Value", "Note"],
        ["设备单价（一次性购置）", "200000", "¥"],
        ["安装/改造费用（一次性）", "20000", "¥"],
        ["培训与初期调试费用（一次性）", "10000", "¥"],
        ["总一次性投入", "=B2+B3+B4", "公式"],
        ["月维护费", "3000", "¥/月"],
        ["月耗材/能耗变化", "1000", "¥/月"],
        ["可替代厨房员工数", "2", "人"],
        ["单个员工税前月薪（含社保）", "6000", "¥/月"],
        ["月度人工节约", "=G7*H7", "公式"],
        ["运营天数/月", "26", "天"],
        ["当前日均订单", "120", "单"],
        ["采用机器人后日均订单", "150", "单"],
        ["日均新增订单", "=L12-L11", "公式"],
        ["平均客单价", "28", "¥/单"],
        ["月度新增营收", "=N13*N14*J10", "公式"],
        ["平均毛利率", "0.60", "0-1"],
        ["月度新增毛利", "=O15*P15", "公式"],
        ["其他月度新增成本/节省", "0", "¥/月"],
        ["月度净收益", "=J9+Q15-J5-J6+Q16", "公式"],
        ["回收期（个月）", "=B5/Q17", "公式"],
        ["年化ROI", "=Q17*12/B5", "公式"],
    ]

    rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>
'''

    content_types = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>
'''

    core = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:creator>GitHub Copilot</dc:creator>
  <cp:lastModifiedBy>GitHub Copilot</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">2026-10-07T00:00:00Z</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">2026-10-07T00:00:00Z</dcterms:modified>
</cp:coreProperties>
'''

    app = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Microsoft Excel</Application>
</Properties>
'''

    worksheet_rows = []
    for r_idx, row in enumerate(rows, start=1):
        cells = []
        for c_idx, value in enumerate(row, start=1):
            cell_ref = f"{chr(64 + c_idx)}{r_idx}"
            if isinstance(value, (int, float)):
                cells.append(f'<c r="{cell_ref}" t="n"><v>{value}</v></c>')
            else:
                if isinstance(value, str) and value.startswith("="):
                    cells.append(f'<c r="{cell_ref}" t="str"><f>{value[1:]}</f><v>{value[1:]}</v></c>')
                else:
                    cells.append(f'<c r="{cell_ref}" t="inlineStr"><is><t>{value}</t></is></c>')
        worksheet_rows.append(f'<row r="{r_idx}">{"".join(cells)}</row>')

    sheet = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    {''.join(worksheet_rows)}
  </sheetData>
</worksheet>
'''

    workbook = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="ROI" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>
'''

    # Minimal workbook rels
    wb_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>
'''

    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("docProps/core.xml", core)
        zf.writestr("docProps/app.xml", app)
        zf.writestr("xl/workbook.xml", workbook)
        zf.writestr("xl/_rels/workbook.xml.rels", wb_rels)
        zf.writestr("xl/worksheets/sheet1.xml", sheet)


def build_pptx(path: Path) -> None:
    """Create a minimal presentation deck using python-pptx if available. Fallback: build XML-based PPTX package."""
    if Presentation is not None:
        prs = Presentation()
        prs.slide_width = 9144000
        prs.slide_height = 5143500
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        title = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(12), Inches(1))
        tf = title.text_frame
        p = tf.paragraphs[0]
        p.text = "用机器人稳定出品，省心提效"
        p.runs[0].font.bold = True
        p.runs[0].font.size = Pt(28)

        subtitle = slide.shapes.add_textbox(Inches(0.6), Inches(1.2), Inches(12), Inches(0.8))
        subtitle.text_frame.text = "门店扩张的关键：降人力、稳口味、提升峰时出餐能力"
        subtitle.text_frame.paragraphs[0].runs[0].font.size = Pt(18)

        left = slide.shapes.add_textbox(Inches(0.7), Inches(2.2), Inches(3.5), Inches(2.2))
        left.text_frame.text = "问题\n• 人员难招、成本高\n• 高峰出餐慢\n• 口味不稳定"
        left.text_frame.paragraphs[0].runs[0].font.size = Pt(18)

        right = slide.shapes.add_textbox(Inches(4.7), Inches(2.2), Inches(6.5), Inches(2.2))
        right.text_frame.text = "方案\n• 自动炒菜机器人\n• 配方标准化\n• 本地化维护与培训"
        right.text_frame.paragraphs[0].runs[0].font.size = Pt(18)

        metrics = slide.shapes.add_textbox(Inches(0.7), Inches(4.7), Inches(11.8), Inches(1.1))
        metrics.text_frame.text = "典型回收期：6-12个月 | 月净收益：¥10k-25k | 出餐能力：提升 30%-60%"
        metrics.text_frame.paragraphs[0].runs[0].font.bold = True
        metrics.text_frame.paragraphs[0].runs[0].font.size = Pt(24)

        footer = slide.shapes.add_textbox(Inches(0.7), Inches(6.3), Inches(11.8), Inches(0.6))
        footer.text_frame.text = "免费 ROI 评估 / 30天试点 / 预约现场演示"
        footer.text_frame.paragraphs[0].runs[0].font.italic = True
        footer.text_frame.paragraphs[0].runs[0].font.size = Pt(16)

        prs.save(path)
        return

    # Fallback minimal PPTX generation using zipfile + Open XML
    slide_xml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr>
        <p:cNvPr id="1" name=""/>
        <p:cNvGrpSpPr/>
        <p:nvPr/>
      </p:nvGrpSpPr>
      <p:grpSpPr>
        <a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm>
      </p:grpSpPr>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Title 1"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="457200" y="274320"/><a:ext cx="8229600" cy="457200"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:ln><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill></a:ln></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="zh-CN" smtClean="0"/><a:t>用机器人稳定出品，省心提效</a:t></a:r><a:endParaRPr lang="zh-CN"/></a:p></p:txBody>
      </p:sp>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="3" name="Body 1"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="457200" y="914400"/><a:ext cx="8229600" cy="600000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:ln><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill></a:ln></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="zh-CN" smtClean="0"/><a:t>门店扩张的关键：降人力、稳口味、提升峰时出餐能力</a:t></a:r><a:endParaRPr lang="zh-CN"/></a:p></p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
  <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>
</p:sld>
'''
    ppt_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/package/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>
'''
    presentation_xml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" saveSubsetFonts="1" autoCompressPictures="0">
  <p:sldMasterIdLst>
    <p:sldMasterId id="2147483648" r:id="rId1"/>
  </p:sldMasterIdLst>
  <p:sldIdLst>
    <p:sldId id="256" r:id="rId2"/>
  </p:sldIdLst>
  <p:sldSz cx="12192000" cy="6858000"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>
'''
    presentation_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/>
</Relationships>
'''
    master = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld name="Office Theme"><p:bg><p:bgPr><a:solidFill><a:schemeClr val="bg1"/></a:solidFill></p:bgPr></p:bg></p:cSld>
  <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>
</p:sldMaster>
'''
    content_types = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>
  <Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>
'''
    app = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Microsoft Office PowerPoint</Application>
</Properties>
'''
    core = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:creator>GitHub Copilot</dc:creator>
  <cp:lastModifiedBy>GitHub Copilot</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">2026-10-07T00:00:00Z</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">2026-10-07T00:00:00Z</dcterms:modified>
</cp:coreProperties>
'''
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", ppt_rels)
        zf.writestr("docProps/core.xml", core)
        zf.writestr("docProps/app.xml", app)
        zf.writestr("ppt/presentation.xml", presentation_xml)
        zf.writestr("ppt/_rels/presentation.xml.rels", presentation_rels)
        zf.writestr("ppt/slideMasters/slideMaster1.xml", master)
        zf.writestr("ppt/slides/slide1.xml", slide_xml)


def build_bundle(output_zip: Path, members: Iterable[Path]) -> None:
    with zipfile.ZipFile(output_zip, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for member in members:
            zf.write(member, arcname=member.name)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = OUT_DIR / "ROI_template.csv"
    xlsx_path = OUT_DIR / "ROI.xlsx"
    pptx_path = OUT_DIR / "pitch.pptx"
    zip_path = OUT_DIR / "robot-sales-materials.zip"

    write_csv_template(csv_path)
    build_minimal_xlsx(xlsx_path)
    build_pptx(pptx_path)
    build_bundle(zip_path, [xlsx_path, pptx_path, csv_path])

    print(f"Created: {csv_path}")
    print(f"Created: {xlsx_path}")
    print(f"Created: {pptx_path}")
    print(f"Created: {zip_path}")
    print("\nNext: run `python3 assets/robot-sales/generate_sales_assets.py` locally to regenerate the Office files if needed.")


if __name__ == "__main__":
    main()
